
admin_article_index:
    path:     /
    defaults: { _controller: "BlogBundle:Article:index" }
    methods:  GET

admin_article_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Article:new" }
    methods:  [GET, POST]

admin_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Article:edit" }
    methods:  [GET, POST]

admin_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Article:delete" }
    methods:  DELETE
    
    
article_add_comment:
    path:     /add-comment/{articleId}
    defaults: { _controller: "BlogBundle:Article:addComment" }
    methods:  POST
