BlogBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime
            
    oneToMany:
        comments:
            targetEntity: BlogBundle\Entity\Comment
            mappedBy: article

    lifecycleCallbacks: {  }
