BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        date:
            type: datetime
        username:
            type: string
    manyToOne:
        article:
            targetEntity: 'BlogBundle\Entity\Article'
            inversedBy: comments 
            joinColumn:
                name: article_id
                referencedColumnName: id
            
    lifecycleCallbacks: {  }
